src/Entity/artist.php
<?php

namespace App\Entity;

use App\Repository\ArtistRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ArtistRepository::class)]
class Artist
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::BIGINT)]
    private ?string $artist_id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\OneToMany(mappedBy: 'artist', targetEntity: Music::class, orphanRemoval: true)]
    private Collection $musics;

    #[ORM\ManyToMany(targetEntity: User::class, mappedBy: 'artists')]
    private Collection $users;

    public function __construct()
    {
        $this->musics = new ArrayCollection();
        $this->users = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getArtistId(): ?string
    {
        return $this->artist_id;
    }

    public function setArtistId(string $artist_id): self
    {
        $this->artist_id = $artist_id;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return Collection<int, Music>
     */
    public function getMusics(): Collection
    {
        return $this->musics;
    }

    public function addMusic(Music $music): self
    {
        if (!$this->musics->contains($music)) {
            $this->musics->add($music);
            $music->setArtist($this);
        }

        return $this;
    }

    public function removeMusic(Music $music): self
    {
        if ($this->musics->removeElement($music)) {
            // set the owning side to null (unless already changed)
            if ($music->getArtist() === $this) {
                $music->setArtist(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, User>
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): self
    {
        if (!$this->users->contains($user)) {
            $this->users->add($user);
            $user->addArtist($this);
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        if ($this->users->removeElement($user)) {
            $user->removeArtist($this);
        }

        return $this;
    }
}

src/Controller/ArtistCrudController.php
<?php

namespace App\Controller;

use App\Entity\Artist;
use App\Form\ArtistType;
use App\Repository\ArtistRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/artistcrud')]
class ArtistCrudController extends AbstractController
{
    #[Route('/', name: 'app_artist_crud_index', methods: ['GET'])]
    public function index(ArtistRepository $artistRepository): Response
    {
        return $this->render('artist_crud/index.html.twig', [
            'artists' => $artistRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_artist_crud_new', methods: ['GET', 'POST'])]
    public function new(Request $request, ArtistRepository $artistRepository): Response
    {
        $artist = new Artist();
        $form = $this->createForm(ArtistType::class, $artist);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $artistRepository->save($artist, true);

            return $this->redirectToRoute('app_artist_crud_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('artist_crud/new.html.twig', [
            'artist' => $artist,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_artist_crud_show', methods: ['GET'])]
    public function show(Artist $artist): Response
    {
        return $this->render('artist_crud/show.html.twig', [
            'artist' => $artist,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_artist_crud_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Artist $artist, ArtistRepository $artistRepository): Response
    {
        $form = $this->createForm(ArtistType::class, $artist);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $artistRepository->save($artist, true);

            return $this->redirectToRoute('app_artist_crud_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('artist_crud/edit.html.twig', [
            'artist' => $artist,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_artist_crud_delete', methods: ['POST'])]
    public function delete(Request $request, Artist $artist, ArtistRepository $artistRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$artist->getId(), $request->request->get('_token'))) {
            $artistRepository->remove($artist, true);
        }

        return $this->redirectToRoute('app_artist_crud_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/artist_crud/_delete_form.html.twig
<form method="post" action="{{ path('app_artist_crud_delete', {'id': artist.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ artist.id) }}">
    <button class="btn">Delete</button>
</form>

templates/artist_crud/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/artist_crud/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Artist{% endblock %}

{% block body %}
    <h1>Edit Artist</h1>

    {{ include('artist_crud/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_artist_crud_index') }}">back to list</a>

    {{ include('artist_crud/_delete_form.html.twig') }}
{% endblock %}

templates/artist_crud/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Artist index{% endblock %}

{% block body %}
    <h1>Artist index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Artist_id</th>
                <th>Name</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for artist in artists %}
            <tr>
                <td>{{ artist.id }}</td>
                <td>{{ artist.artistId }}</td>
                <td>{{ artist.name }}</td>
                <td>
                    <a href="{{ path('app_artist_crud_show', {'id': artist.id}) }}">show</a>
                    <a href="{{ path('app_artist_crud_edit', {'id': artist.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_artist_crud_new') }}">Create new</a>
{% endblock %}

templates/artist_crud/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Artist{% endblock %}

{% block body %}
    <h1>Create new Artist</h1>

    {{ include('artist_crud/_form.html.twig') }}

    <a href="{{ path('app_artist_crud_index') }}">back to list</a>
{% endblock %}

templates/artist_crud/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Artist{% endblock %}

{% block body %}
    <h1>Artist</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ artist.id }}</td>
            </tr>
            <tr>
                <th>Artist_id</th>
                <td>{{ artist.artistId }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ artist.name }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_artist_crud_index') }}">back to list</a>

    <a href="{{ path('app_artist_crud_edit', {'id': artist.id}) }}">edit</a>

    {{ include('artist_crud/_delete_form.html.twig') }}
{% endblock %}